/**
 * Typed API client.
 *
 * Every type here is generated from the backend's OpenAPI schema
 * (`schema.ts`, regenerated by `npm run gen:api`). The previous client
 * hand-maintained its own copies of four backend shapes and reconciled a
 * snake_case and a camelCase variant of the same object with a mapper that
 * silently dropped fields. Those copies are gone: if the backend changes a
 * field, this file stops compiling.
 */

import type { components } from "./schema";

export type AnalysisResult = components["schemas"]["AnalysisResult"];
export type Finding = components["schemas"]["FindingOut"];
export type JobRef = components["schemas"]["JobRef"];
export type JobSummary = components["schemas"]["JobSummary"];
export type Section = components["schemas"]["SectionOut"];
export type Health = components["schemas"]["HealthOut"];
export type Span = components["schemas"]["SpanOut"];
export type Attention = components["schemas"]["AttentionScore"];
export type RequestKind = components["schemas"]["RequestKind"];
export type ChangeType = components["schemas"]["ChangeType"];

const RAW_BASE = import.meta.env.VITE_API_URL ?? "";
// Normalised once, and every call uses it. The previous client had two
// helpers that reached for the un-normalised value instead, so configuring
// the base URL with a trailing path segment produced a doubled path and
// broke those endpoints.
export const API_BASE = RAW_BASE.replace(/\/+$/, "");

const API_KEY = import.meta.env.VITE_API_KEY ?? "";

export class ApiError extends Error {
  constructor(
    readonly status: number,
    message: string,
  ) {
    super(message);
    this.name = "ApiError";
  }
}

function headers(extra?: HeadersInit): HeadersInit {
  return {
    "Content-Type": "application/json",
    ...(API_KEY ? { "X-API-Key": API_KEY } : {}),
    ...extra,
  };
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${API_BASE}${path}`, {
    ...init,
    headers: headers(init?.headers),
  });

  if (!response.ok) {
    throw new ApiError(response.status, await errorText(response));
  }
  return response.status === 204 ? (undefined as T) : ((await response.json()) as T);
}

/** FastAPI returns `detail` as a string, or as a list for 422. */
async function errorText(response: Response): Promise<string> {
  try {
    const body = await response.json();
    const detail = body?.detail;
    if (typeof detail === "string") return detail;
    if (Array.isArray(detail)) {
      return detail.map((d: { msg?: string }) => d.msg ?? JSON.stringify(d)).join("; ");
    }
  } catch {
    // Not JSON. Fall through to the status line.
  }
  return `${response.status} ${response.statusText}`;
}

export function submitAnalysis(body: {
  ticker: string;
  kind?: RequestKind;
  max_sections?: number;
}): Promise<JobRef> {
  return request<JobRef>("/analyses", { method: "POST", body: JSON.stringify(body) });
}

export function getAnalysis(jobId: string): Promise<AnalysisResult> {
  return request<AnalysisResult>(`/analyses/${jobId}`);
}

export function listAnalyses(limit = 25): Promise<JobSummary[]> {
  return request<JobSummary[]>(`/analyses?limit=${limit}`);
}

export function cancelAnalysis(jobId: string): Promise<void> {
  return request<void>(`/analyses/${jobId}`, { method: "DELETE" });
}

export function getSection(jobId: string, accession: string, sectionId: string): Promise<Section> {
  return request<Section>(
    `/analyses/${jobId}/sections/${encodeURIComponent(accession)}/${encodeURIComponent(sectionId)}`,
  );
}

export function getHealth(): Promise<Health> {
  return request<Health>("/health");
}

export type StreamEvent =
  | { type: "status"; status: string; ticker?: string }
  | { type: "node_start"; node: string }
  | { type: "node_end"; node: string }
  | { type: "heartbeat"; at: string }
  | { type: "complete"; findings: number; errors: string[] }
  | { type: "error"; message: string }
  | { type: "result"; result: AnalysisResult };

/**
 * Follow a run.
 *
 * Read with fetch rather than EventSource because EventSource cannot send
 * headers, and the API key has to travel on the request.
 *
 * The promise settles exactly once, on the terminal event or on abort. The
 * previous implementation could finish without a terminal event and leave
 * the caller's `isAnalyzing` true forever with nothing shown.
 */
export async function streamAnalysis(
  jobId: string,
  onEvent: (event: StreamEvent) => void,
  signal?: AbortSignal,
): Promise<AnalysisResult | null> {
  const response = await fetch(`${API_BASE}/analyses/${jobId}/stream`, {
    headers: headers({ Accept: "text/event-stream" }),
    signal,
  });
  if (!response.ok) throw new ApiError(response.status, await errorText(response));
  if (!response.body) throw new ApiError(0, "stream has no body");

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let result: AnalysisResult | null = null;

  try {
    for (;;) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });

      // SSE frames are separated by a blank line. Keep the trailing partial.
      const frames = buffer.split("\n\n");
      buffer = frames.pop() ?? "";

      for (const frame of frames) {
        const parsed = parseFrame(frame);
        if (!parsed) continue;
        if (parsed.event === "result") {
          result = parsed.data as AnalysisResult;
          onEvent({ type: "result", result });
        } else {
          onEvent({ type: parsed.event, ...parsed.data } as StreamEvent);
        }
      }
    }
  } finally {
    reader.cancel().catch(() => undefined);
  }
  return result;
}

function parseFrame(frame: string): { event: string; data: Record<string, unknown> } | null {
  let event = "message";
  const dataLines: string[] = [];
  for (const line of frame.split("\n")) {
    if (line.startsWith("event:")) event = line.slice(6).trim();
    else if (line.startsWith("data:")) dataLines.push(line.slice(5).trim());
  }
  if (dataLines.length === 0) return null;
  try {
    return { event, data: JSON.parse(dataLines.join("\n")) };
  } catch {
    return null;
  }
}

/** Human label for a pipeline node, for the progress list. */
export const NODE_LABELS: Record<string, string> = {
  resolve_company: "Resolving filer",
  ingest_filings: "Fetching filings",
  run_diff: "Comparing sections",
  run_novelty: "Checking first use",
  run_peer: "Checking peers",
  measure_attention: "Measuring attention",
  finalize: "Verifying citations",
};
