/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_analyses_get"];
        put?: never;
        /**
         * Submit Analysis
         * @description Start a run and return immediately.
         *
         *     202 rather than 200: the work is accepted, not finished. Progress is on
         *     the stream endpoint and the result on the job endpoint.
         */
        post: operations["submit_analysis_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_analyses__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Analysis */
        delete: operations["cancel_analysis_analyses__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Analysis
         * @description Server-sent events for one run.
         *
         *     The stream always terminates with a `complete` or `error` event, so a
         *     client never has to guess whether a silent connection means work in
         *     progress or a dead backend.
         */
        get: operations["stream_analysis_analyses__job_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{job_id}/sections/{accession}/{section_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Section
         * @description The stored text a finding's span points into.
         *
         *     This is what makes a citation checkable in the UI: the client resolves
         *     start and end against exactly the text the engine diffed.
         */
        get: operations["get_section_analyses__job_id__sections__accession___section_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Watchlist */
        get: operations["list_watchlist_watchlist_get"];
        put?: never;
        /**
         * Add To Watchlist
         * @description Watch a ticker.
         *
         *     The first sweep records the newest filing as a baseline without alerting,
         *     so adding a ticker does not immediately report its whole history.
         */
        post: operations["add_to_watchlist_watchlist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove From Watchlist */
        delete: operations["remove_from_watchlist_watchlist__ticker__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/poller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poller Status */
        get: operations["poller_status_watchlist_poller_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/watchlist/poller/sweep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sweep Now
         * @description Run one sweep immediately, rather than waiting for the interval.
         */
        post: operations["sweep_now_watchlist_poller_sweep_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResult
         * @description A completed run.
         *
         *     `errors` is populated rather than hidden. Partial failure is visible to
         *     the caller instead of being swallowed into a plausible-looking default,
         *     which is how a hardcoded sentiment string shipped in every memo for the
         *     life of the previous system.
         */
        AnalysisResult: {
            /** Job Id */
            job_id: string;
            /** Ticker */
            ticker: string;
            /** Status */
            status: string;
            /** Company Name */
            company_name: string | null;
            /** Cik */
            cik: string | null;
            /** Sic */
            sic: string | null;
            current_filing: components["schemas"]["Filing"] | null;
            prior_filing: components["schemas"]["Filing"] | null;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
            attention: components["schemas"]["AttentionScore"] | null;
            /** Errors */
            errors: string[];
            /** Timings */
            timings: components["schemas"]["NodeTimingOut"][];
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /**
             * Ticker
             * @description US-listed ticker, for example AAPL
             */
            ticker: string;
            /** @default full */
            kind: components["schemas"]["RequestKind"];
            /**
             * Max Sections
             * @default 4
             */
            max_sections: number;
        };
        /**
         * AttentionScore
         * @description Aggregate across whatever sources were available.
         */
        AttentionScore: {
            /** Ticker */
            ticker: string;
            /** Window Days */
            window_days: number;
            /** Signals */
            signals: components["schemas"]["AttentionSignal"][];
            /** Available Sources */
            readonly available_sources: components["schemas"]["AttentionSourceName"][];
            /** Total Mentions */
            readonly total_mentions: number;
            /**
             * Score
             * @description Attention in [0, 1], from the mean z-score across live sources.
             *
             *     A logistic squash keeps a single viral source from saturating the
             *     result while still separating "quiet" from "loud".
             */
            readonly score: number;
            /** Net Sentiment */
            readonly net_sentiment: number;
            /**
             * Is Degraded
             * @description True when some configured source failed, so the score understates.
             */
            readonly is_degraded: boolean;
        };
        /**
         * AttentionSignal
         * @description One source's reading for one ticker over one window.
         */
        AttentionSignal: {
            source: components["schemas"]["AttentionSourceName"];
            /** Ticker */
            ticker: string;
            /** Window Days */
            window_days: number;
            /** Mention Count */
            mention_count: number;
            /** Baseline Daily Mean */
            baseline_daily_mean: number;
            /** Baseline Daily Stdev */
            baseline_daily_stdev: number;
            /** Sentiment Counts */
            sentiment_counts: {
                [key: string]: number;
            };
            /**
             * Sampled At
             * Format: date-time
             */
            sampled_at: string;
            /** Error */
            error: string | null;
            /** Available */
            readonly available: boolean;
            /**
             * Z Score
             * @description Standard deviations above the ticker's own baseline.
             *
             *     Guarded against a zero stdev, which happens for quiet tickers where
             *     every day in the baseline window had the same count.
             */
            readonly z_score: number;
            /**
             * Net Sentiment
             * @description Positive share minus negative share, in [-1, 1]. 0 when unknown.
             */
            readonly net_sentiment: number;
        };
        /**
         * AttentionSourceName
         * @enum {string}
         */
        AttentionSourceName: "bluesky" | "hackernews" | "reddit" | "news";
        /**
         * ChangeType
         * @enum {string}
         */
        ChangeType: "added" | "removed" | "reworded" | "moved";
        /** Filing */
        Filing: {
            /** Accession */
            accession: string;
            /** Cik */
            cik: string;
            /** Ticker */
            ticker: string;
            form: components["schemas"]["Form"];
            /**
             * Filing Date
             * Format: date
             */
            filing_date: string;
            /** Period Of Report */
            period_of_report?: string | null;
            /** Primary Doc Url */
            primary_doc_url: string;
            /** Fetched At */
            fetched_at?: string | null;
            /** Char Length */
            char_length?: number | null;
            /**
             * Fiscal Label
             * @description Human label used to describe which filing a finding came from.
             */
            readonly fiscal_label: string;
        };
        /**
         * FindingKind
         * @enum {string}
         */
        FindingKind: "diff" | "novelty" | "peer";
        /** FindingOut */
        FindingOut: {
            /** Id */
            id: string;
            kind: components["schemas"]["FindingKind"];
            /** Ticker */
            ticker: string;
            /** Cik */
            cik: string;
            section_id: components["schemas"]["SectionId"];
            change_type: components["schemas"]["ChangeType"] | null;
            current_span: components["schemas"]["SpanOut"] | null;
            prior_span: components["schemas"]["SpanOut"] | null;
            /** Current Accession */
            current_accession: string | null;
            /** Prior Accession */
            prior_accession: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            materiality: components["schemas"]["Materiality"];
            /** Novelty Phrase */
            novelty_phrase: string | null;
            /** Novelty First Seen */
            novelty_first_seen: string | null;
            /** Peer Ciks */
            peer_ciks: string[];
            /** Peer Total */
            peer_total: number | null;
        };
        /**
         * Form
         * @enum {string}
         */
        Form: "10-K" | "10-Q" | "8-K" | "4";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
            /** Git Sha */
            git_sha: string;
            /** Checkpointer */
            checkpointer: string;
            /** Attention Sources */
            attention_sources: string[];
        };
        /**
         * JobRef
         * @description What a submit returns. The work continues after the response.
         */
        JobRef: {
            /** Job Id */
            job_id: string;
            /** Ticker */
            ticker: string;
            kind: components["schemas"]["RequestKind"];
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Stream Url */
            stream_url: string;
        };
        /** JobSummary */
        JobSummary: {
            /** Job Id */
            job_id: string;
            /** Ticker */
            ticker: string;
            kind: components["schemas"]["RequestKind"];
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Error */
            error: string | null;
            /**
             * Finding Count
             * @default 0
             */
            finding_count: number;
        };
        /**
         * Materiality
         * @description Why a change is worth surfacing, not just that it is.
         */
        Materiality: {
            /** Score */
            score: number;
            /** Reasons */
            reasons?: string[];
            /** Band */
            readonly band: string;
        };
        /**
         * NewFilingOut
         * @description A filing the poller saw that the watcher has not been told about.
         */
        NewFilingOut: {
            /** Ticker */
            ticker: string;
            /** Cik */
            cik: string;
            /** Accession */
            accession: string;
            /** Form */
            form: string;
            /**
             * Filed
             * Format: date
             */
            filed: string;
            /** Title */
            title: string;
            /** Link */
            link: string;
        };
        /** NodeTimingOut */
        NodeTimingOut: {
            /** Node */
            node: string;
            /** Seconds */
            seconds: number;
        };
        /** PollerStatusOut */
        PollerStatusOut: {
            /** Running */
            running: boolean;
            /** Interval Seconds */
            interval_seconds: number;
            /** Last Sweep At */
            last_sweep_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Pending */
            pending: components["schemas"]["NewFilingOut"][];
        };
        /**
         * RequestKind
         * @description What the caller asked for.
         *
         *     Drives conditional routing. Running every engine on every request is what
         *     the old graph did, and most of it was wasted: a document lookup does not
         *     need peer analysis.
         * @enum {string}
         */
        RequestKind: "diff" | "novelty" | "peer" | "full";
        /**
         * SectionId
         * @description Canonical section identity, stable across years.
         *
         *     Filings renumber and retitle items between years, so the raw heading is
         *     not a usable key. The parser maps whatever the document says onto one of
         *     these, and cross-year alignment joins on it.
         * @enum {string}
         */
        SectionId: "item_1_business" | "item_1a_risk_factors" | "item_1b_unresolved_staff_comments" | "item_1c_cybersecurity" | "item_2_properties" | "item_3_legal_proceedings" | "item_7_mda" | "item_7a_market_risk" | "item_8_financial_statements" | "item_9a_controls" | "part1_item2_mda" | "part2_item1a_risk_factors" | "part2_item1_legal_proceedings" | "other";
        /**
         * SectionOut
         * @description Section text, for resolving a citation in the UI.
         */
        SectionOut: {
            /** Accession */
            accession: string;
            section_id: components["schemas"]["SectionId"];
            /** Heading */
            heading: string;
            /** Text */
            text: string;
            /** Char Length */
            char_length: number;
        };
        /**
         * Sentiment
         * @enum {string}
         */
        Sentiment: "positive" | "neutral" | "negative";
        /**
         * SpanOut
         * @description A citation. Every field needed to resolve it back to source text.
         */
        SpanOut: {
            /** Accession */
            accession: string;
            section_id: components["schemas"]["SectionId"];
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Quote */
            quote: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WatchRequest */
        WatchRequest: {
            /** Ticker */
            ticker: string;
            /** Forms */
            forms?: string[];
        };
        /** WatchedOut */
        WatchedOut: {
            /** Ticker */
            ticker: string;
            /** Cik */
            cik: string | null;
            /** Forms */
            forms: string[];
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Last Seen */
            last_seen: {
                [key: string]: string;
            };
            /** Last Checked At */
            last_checked_at: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_analyses_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_analysis_analyses_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_analyses__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_analysis_analyses__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_analysis_analyses__job_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_section_analyses__job_id__sections__accession___section_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                job_id: string;
                accession: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_watchlist_watchlist_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchedOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_to_watchlist_watchlist_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WatchedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_from_watchlist_watchlist__ticker__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    poller_status_watchlist_poller_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollerStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sweep_now_watchlist_poller_sweep_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewFilingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
